### ISSUE TITLE
Non-zero exit code encountered during exit function

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/nvidia-auto-installer-for-fedora-linux#1]
When packaged using PyInstaller, `exit()` is not recognized
```
Traceback (most recent call last):
  File "MainFunction.py", line 50, in <module>
  File "MainFunction.py", line 47, in main
NameError: name 'exit' is not defined
[5385] Failed to execute script MainFunction
```

**Comment by gridhead** [comment]
Replaced all `exit()` calls with `sys.exit(0)`. The issue is fixed for now as of the commit `3f6cfc1`.
